# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 7.4

services:
  - mysql

env:
  - DB=mysql

install:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - composer tester

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    -   name: Liquid Design Code Style
        php: 7.4
        script:
          - composer phpcs
    -   name: Static analysis
        php: 7.4
        script:
          - composer phpstan

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
